---
title: "Getting started with R - Code and exercises"
author: "Dr. Carina Nigg & Dr. Judith Boumann"
date: 4 January 2025
format:
  html:
   code-fold: true
   toc: true
   toc-expand: 1
   toc-title: Contents
   toc-location: left
   number-sections: true
   embed-resources: true
---


# Introduction and R setup


Install and load packages

```{r packages}
#| output: false
#| warning: false

# List of required packages
packages <- c("haven", "tidyverse", "table1", "writexl")

# Function to check if a package is installed and install it if not
install_if_missing <- function(package) {
  if (!require(package, character.only = TRUE)) {
    install.packages(package, dependencies = TRUE)
  }
  library(package, character.only = TRUE)
}

# Loop through each package and install if missing, then load the package
for (pkg in packages) {
  install_if_missing(pkg)
}

```


Set system language to English

```{r set english}
Sys.setenv(LANG = "en")
```

Set directories

```{r set directories and project folders}

# Set the project root directory
d_proj <- "C:/Users/cn23r745/OneDrive - Universitaet Bern/_Teaching/Introduction_to_R/Code/getting_started_with_R/data"

# Basic folders
# Directory for original data
d_oridata <- file.path(d_proj, "01_oridata")
# Directory for edited data
d_data <- file.path(d_proj, "02_data")
# Directory for R scripts
d_script <- file.path(d_proj, "03_script")
# Directory for R output
d_output <- file.path(d_proj, "04_output")


# Create a vector with all directories
dirs <- c(d_oridata, d_data, d_script, d_output)

# Loop through the directories and create them if they don't exist
for (dir in dirs) {
  if (!dir.exists(dir)) {
    dir.create(dir, recursive = TRUE)
  }
}

```

# 2 Import data

```{r}
#| include: FALSE

# Preparation of NHANES dataset (2017-2018) for class

## 1 Demographic data
nhanes_demo <- read_xpt(file.path(d_oridata, "DEMO_J.xpt"))
dim(nhanes_demo)

demo <- nhanes_demo %>% # select only relevant variables
        select(SEQN, RIAGENDR, RIDAGEYR, RIDRETH1, DMDEDUC2, INDHHIN2)

## 2 Examination data

# height, weight, bmi
nhanes_body <- read_xpt(file.path(d_oridata, "BMX_J.xpt"))
dim(nhanes_body)

body <- nhanes_body %>% # select only relevant variables
        select(SEQN, BMXWT, BMXHT, BMXBMI)

# blood pressure
nhanes_bloodpressure <- read_xpt(file.path(d_oridata, "BPX_J.xpt"))
dim(nhanes_bloodpressure)

blood <- nhanes_bloodpressure %>%
         select(SEQN, BPXSY1, BPXDI1, BPXPLS)

## 3 Questionnaire data
nhanes_smoking <- read_xpt(file.path(d_oridata, "SMQ_J.xpt"))
dim(nhanes_smoking)

smoking <- nhanes_smoking %>% # select only relevant variables
           select(SEQN, SMQ020, SMQ040, SMQ900)


# Join to one dataframe
nhanes <- demo %>%
  left_join(body, by = "SEQN") %>%
  left_join(blood, by = "SEQN") %>%
  left_join(smoking, by = "SEQN")
glimpse(nhanes)

# Export to xlx file
write_xlsx(nhanes, file.path(d_data, "nhanes_for_R.xlsx"))


```








